import 'package:hive_flutter/hive_flutter.dart';
import '../models/score_record.dart';
import '../models/ability_snapshot.dart';
import '../models/user_profile.dart';

/// Hive box names — single source of truth
abstract final class HiveBoxes {
  static const String profile = 'profile';
  static const String scores = 'scores';
  static const String ability = 'ability';
}

/// Initialize all Hive boxes and register adapters
Future<void> initHive() async {
  await Hive.initFlutter();

  // Register type adapters (generated by hive_generator)
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(UserProfileAdapter());
  }
  if (!Hive.isAdapterRegistered(1)) {
    Hive.registerAdapter(ScoreRecordAdapter());
  }
  if (!Hive.isAdapterRegistered(3)) {
    Hive.registerAdapter(AbilitySnapshotAdapter());
  }

  // Open boxes
  await Hive.openBox<UserProfile>(HiveBoxes.profile);
  await Hive.openBox<ScoreRecord>(HiveBoxes.scores);
  await Hive.openBox<AbilitySnapshot>(HiveBoxes.ability);

  // One-time data migration: normalize historical game IDs.
  await _migrateLegacyScoreGameIds();
}

/// Typed box accessors
Box<UserProfile> get profileBox => Hive.box<UserProfile>(HiveBoxes.profile);
Box<ScoreRecord> get scoresBox => Hive.box<ScoreRecord>(HiveBoxes.scores);
Box<AbilitySnapshot> get abilityBox => Hive.box<AbilitySnapshot>(HiveBoxes.ability);

Future<void> _migrateLegacyScoreGameIds() async {
  const canonicalByNormalized = <String, String>{
    'schultegrid': 'schulte_grid',
    'reactiontime': 'reaction_time',
    'numbermemory': 'number_memory',
    'strooptest': 'stroop_test',
    'visualmemory': 'visual_memory',
    'sequencememory': 'sequence_memory',
    'numbermatrix': 'number_matrix',
    'reversememory': 'reverse_memory',
    'slidingpuzzle': 'sliding_puzzle',
    'towerofhanoi': 'tower_of_hanoi',
    'schulte': 'schulte_grid',
    'reaction': 'reaction_time',
    'stroop': 'stroop_test',
    'hanoi': 'tower_of_hanoi',
  };

  final box = scoresBox;
  final keys = box.keys.toList(growable: false);

  for (final key in keys) {
    final record = box.get(key);
    if (record == null) continue;

    final normalized = record.gameId
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]'), '');
    final canonical = canonicalByNormalized[normalized];
    if (canonical == null || canonical == record.gameId) continue;

    final migrated = ScoreRecord(
      gameId: canonical,
      score: record.score,
      accuracy: record.accuracy,
      timestamp: record.timestamp,
      difficulty: record.difficulty,
      metadata: Map<String, dynamic>.from(record.metadata),
    );

    await box.put(key, migrated);
  }
}
