import 'package:hive_flutter/hive_flutter.dart';
import '../models/score_record.dart';
import '../models/ability_snapshot.dart';
import '../models/user_profile.dart';

/// Hive box names — single source of truth
abstract final class HiveBoxes {
  static const String profile = 'profile';
  static const String scores = 'scores';
  static const String ability = 'ability';
}

/// Initialize all Hive boxes and register adapters
Future<void> initHive() async {
  await Hive.initFlutter();

  // Register type adapters (generated by hive_generator)
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(UserProfileAdapter());
  }
  if (!Hive.isAdapterRegistered(1)) {
    Hive.registerAdapter(ScoreRecordAdapter());
  }
  if (!Hive.isAdapterRegistered(3)) {
    Hive.registerAdapter(AbilitySnapshotAdapter());
  }

  // Open boxes
  await Hive.openBox<UserProfile>(HiveBoxes.profile);
  await Hive.openBox<ScoreRecord>(HiveBoxes.scores);
  await Hive.openBox<AbilitySnapshot>(HiveBoxes.ability);
}

/// Typed box accessors
Box<UserProfile> get profileBox => Hive.box<UserProfile>(HiveBoxes.profile);
Box<ScoreRecord> get scoresBox => Hive.box<ScoreRecord>(HiveBoxes.scores);
Box<AbilitySnapshot> get abilityBox => Hive.box<AbilitySnapshot>(HiveBoxes.ability);
